name: DrChat
version: ${project.version}
main: org.acornmc.drchat.DrChat
api-version: 1.17
authors: [ DrBot ]
description: antispam with DiscordSRV support
softdepend:
  - DiscordSRV
  - Essentials
  - Litebans
  - Vault
  - LuckPerms
commands:
  drchat:
    description: manage drchat
    usage: /<command> reload|freeze
    permission: drchat.command
  staffchat:
    desciption: use staffchat
    usage: /<command> message
    permission: drchat.staffchat
    aliases: [h]
  prefix:
    description: change prefix
    usage: /<command>
    permission: drchat.prefix
permissions:
  drchat.command:
    default: op
  drchat.freeze:
    default: op
    children:
      - drchat.command
  drchat.reload:
    default: op
    children:
      - drchat.command
  drchat.staffchat:
    default: op
  drchat.prefix:
    default: op
  drchat.earnchatmoney:
    default: false
  drchat.resetnickonrename:
    default: false
