name: DrChat
version: ${project.version}
main: org.acornmc.drchat.DrChat
api-version: 1.17
authors: [ DrBot ]
description: antispam with DiscordSRV support
softdepend:
  - DiscordSRV
  - Essentials
  - Litebans
commands:
  drchat:
    description: reload drchat
    usage: /<command> reload
    permission: drchat.reload
  staffchat:
    desciption: use staffchat
    usage: /<command> message
    permission: drchat.staffchat
    aliases: [h]
  prefix:
    description: change prefix
    usage: /<command> prefix
    permission: drchat.prefix
permissions:
  drchat.reload:
    default: op
  drchat.staffchat:
    default: op
  drchat.resetnickonnamechange:
    default: false
